name: NoSQL-final

services:
  db_mongo:
    build: ./_CI/db/mongo
    container_name: mongo_app
    ports:
      - ${DB_MONGO_PORT_IN}:${DB_MONGO_PORT_OUT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  data_generator:
    container_name: data_generator_app
    build:
      context: ./
      dockerfile: ./_CI/generator/Dockerfile
    depends_on:
      - db_mongo

volumes:
  mongo_data: